<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Zenith.NET\Zenith.NET.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Silk.NET.MoltenVK.Native" />
        <PackageReference Include="Silk.NET.Vulkan" />
        <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
        <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" />
    </ItemGroup>

    <Import Project="..\NuGet.Packaging.props" />

</Project>
