<Project>

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
        <PackageOutputPath>$(MSBuildThisFileDirectory)..\.nuget</PackageOutputPath>

        <Version>1.1.0</Version>
        <Authors>qian-o</Authors>
        <Copyright>Copyright (c) 2026 qian-o</Copyright>
        <Description>A cross-platform rendering hardware interface for .NET with a shared C# API for graphics and compute across DirectX 12, Metal 4, and Vulkan 1.4.</Description>

        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/qian-o/Zenith.NET.git</RepositoryUrl>

        <PackageIcon>Zenith.NET.png</PackageIcon>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>RHI;Graphics;GPU;Rendering;CSharp</PackageTags>
        <PackageProjectUrl>https://qian-o.github.io/Zenith.NET</PackageProjectUrl>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="$(MSBuildThisFileDirectory)..\documents\images\Zenith.NET.png" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>