<Project>

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>

        <!-- Output -->
        <PackageOutputPath>$(MSBuildThisFileDirectory)..\.nuget</PackageOutputPath>

        <!-- Package Metadata -->
        <Version>0.0.6</Version>
        <Authors>qian-o</Authors>
        <Copyright>Copyright (c) 2026 qian-o</Copyright>
        <Description>Zenith.NET is a modern, cross-platform graphics and compute library for .NET. It provides a unified GPU programming interface supporting DirectX12, Metal, and Vulkan backends.</Description>

        <!-- Repository Information -->
        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/qian-o/Zenith.NET.git</RepositoryUrl>

        <!-- Package Content -->
        <PackageIcon>Zenith.NET.png</PackageIcon>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>DirectX12;Metal;Vulkan;ImageSharp;ImGui;Skia;Slang;Avalonia;Maui;Uno;WinForms;WinUI;WPF;GPU;Native</PackageTags>
        <PackageProjectUrl>https://qian-o.github.io/Zenith.NET</PackageProjectUrl>

        <!-- Debug Symbols & Source Link -->
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <!-- Only auto-generate package on Release builds -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="$(MSBuildThisFileDirectory)..\documents\images\Zenith.NET.png" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>