<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Zenith.NET\Zenith.NET.csproj" />
    </ItemGroup>

    <Import Project="..\..\NuGet.Packaging.props" />

</Project>
