name: Bug report
description: Create a report to help us improve
title: "Bug Report: "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: In a few sentences, please enter a short, clear description of the bug.
      placeholder: E.g. When clicking on a togggle button, '...' happens instead of '...' when '...' is enabled.
