<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(StandardTargetFramework)</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);$(StandardTargetFramework)-windows10.0.19041.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Zenith.NET.Views\Zenith.NET.Views.csproj" />
    </ItemGroup>

    <Choose>
        <When Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
            <ItemGroup>
                <PackageReference Include="Microsoft.WindowsAppSDK" />
                <PackageReference Include="Silk.NET.Direct3D11" />
            </ItemGroup>
        </When>
        <Otherwise>
            <ItemGroup>
                <PackageReference Include="Uno.WinUI" />
            </ItemGroup>
        </Otherwise>
    </Choose>

    <Import Project="..\..\NuGet.Packaging.props" />

</Project>
