<Project>

    <Import Project="..\Directory.Packages.props" />

    <ItemGroup>
        <PackageVersion Include="Avalonia.Desktop" Version="11.3.8" />
        <PackageVersion Include="Avalonia.Diagnostics" Version="11.3.8" />
        <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.3.8" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.8" />
        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageVersion Include="Microsoft.Maui.Essentials" Version="10.0.10" />
        <PackageVersion Include="SharpGLTF.Toolkit" Version="1.0.5" />
        <PackageVersion Include="Silk.NET.Input" Version="2.22.0" />
        <PackageVersion Include="Silk.NET.Windowing" Version="2.22.0" />
    </ItemGroup>

</Project>