<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Hexa.NET.ImGui" />
        <PackageReference Include="Hexa.NET.ImGuizmo" />
        <PackageReference Include="Hexa.NET.ImNodes" />
        <PackageReference Include="Hexa.NET.ImPlot" />
    </ItemGroup>

</Project>
