<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
        <NoWarn>IDE0130</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Slangc.NET" />
    </ItemGroup>

    <Import Project="..\NuGet.Packaging.props" />

</Project>
