<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Zenith.NET\Zenith.NET.csproj" />
    </ItemGroup>

    <Import Project="..\..\NuGet.Packaging.props" />

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="ThirdParty\SGSR-LICENSE.txt" Pack="true" PackagePath="third-party-notices\SGSR-LICENSE.txt" />
    </ItemGroup>

</Project>
