name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Workload
        run: dotnet workload install maui
          
      - name: Build
        run: dotnet build /p:EnableWindowsTargeting=true
    
